name: 'gitglean workflow'
run-name: 'gitglean: Update README.md'
on:
    workflow_dispatch:
    push:
    schedule:
      - cron: '0 0 * * *'
jobs:
    run-auto-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: IsaacDennis/gitglean@master
          with:
            username: 'IsaacDennis'
            template-path: ${{ github.workspace }}/README.template
            output-path: ${{ github.workspace }}/README.md
            format: 'md'
            page: 1
            perPage: 8
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: '[gitglean] Update README.md'
